module.exports = [
  {
    id: 1,
    icon: 'laptop',
    name: '首页',
    router: '/dashboard',
  },

  // {
  //   id: 2,
  //   bpid: 1,
  //   name: '人员管理',
  //   icon: 'user'
  //   // router: '/user',
  // },
  // {
  //   id: 21,
  //   bpid: 2,
  //   mpid: 2,
  //   name: '人员管理',
  //   // icon: 'user',
  //   router: '/user/manage'
  // },
  // {
  //   id: 22,
  //   mpid: 2,
  //   bpid:2,
  //   name: '离职人员项目',
  //   router: '/user/quit'
  // },
  {
    id: 3,
    bpid: 1,
    name: '账号管理',
    icon: 'api',
    router: '/request',
  },
  {
    id:4,
    bpid: 1,
    name: '我的账单',
    icon: 'setting',
    router: '/supervisor',
  },
  {
    id:7,
    bpid: 1,
    name: '快捷语管理',
    icon: 'area-chart',
    router: '/quick',
  },

  {
    id:8,
    bpid: 1,
    name: '项目管理',
    icon: 'setting',
    // router: '/house',
  },
  {
    id:81,
    bpid: 8,
    mpid: 8,
    name: '创建项目',
    router: '/house/create',
  },
  {
    id:82,
    bpid: 8,
    mpid: 8,
    name: '审核项目',
    router: '/house/review',
  },
  {
    id:83,
    bpid: 8,
    mpid: 8,
    name: '公开请求',
    router: '/house/open',
  },
  {
    id:84,
    bpid: 8,
    mpid: 8,
    name: '项目详情',
    router: '/house/detail',
  },

]



// {
//   id: 21,
//   mpid: -1,
//   bpid: 2,
//   name: 'User Detail',
//   router: '/user/:id',
// },
// {
//   id: 4,
//   bpid: 1,
//   name: 'UI Element',
//   icon: 'camera-o',
// },
// {
//   id: 41,
//   bpid: 4,
//   mpid: 4,
//   name: 'IconFont',
//   icon: 'heart-o',
//   router: '/UIElement/iconfont',
// },
// {
//   id: 42,
//   bpid: 4,
//   mpid: 4,
//   name: 'DataTable',
//   icon: 'database',
//   router: '/UIElement/dataTable',
// },
// {
//   id: 43,
//   bpid: 4,
//   mpid: 4,
//   name: 'DropOption',
//   icon: 'bars',
//   router: '/UIElement/dropOption',
// },
// {
//   id: 44,
//   bpid: 4,
//   mpid: 4,
//   name: 'Search',
//   icon: 'search',
//   router: '/UIElement/search',
// },
// {
//   id: 45,
//   bpid: 4,
//   mpid: 4,
//   name: 'Editor',
//   icon: 'edit',
//   router: '/UIElement/editor',
// },
// {
//   id: 46,
//   bpid: 4,
//   mpid: 4,
//   name: 'layer (Function)',
//   icon: 'credit-card',
//   router: '/UIElement/layer',
// },
// {
//   id: 5,
//   bpid: 1,
//   name: 'Recharts',
//   icon: 'code-o',
// },
// {
//   id: 51,
//   bpid: 5,
//   mpid: 5,
//   name: 'LineChart',
//   icon: 'line-chart',
//   router: '/chart/lineChart',
// },
// {
//   id: 52,
//   bpid: 5,
//   mpid: 5,
//   name: 'BarChart',
//   icon: 'bar-chart',
//   router: '/chart/barChart',
// },
// {
//   id: 53,
//   bpid: 5,
//   mpid: 5,
//   name: 'AreaChart',
//   icon: 'area-chart',
//   router: '/chart/areaChart',
// },
// {
//   id: 6,
//   bpid: 1,
//   name: 'Test Navigation',
//   icon: 'setting',
// },
// {
//   id: 61,
//   bpid: 6,
//   mpid: 6,
//   name: 'Test Navigation1',
//   router: '/navigation/navigation1',
// },
// {
//   id: 62,
//   bpid: 6,
//   mpid: 6,
//   name: 'Test Navigation2',
//   router: '/navigation/navigation2',
// },
// {
//   id: 621,
//   bpid: 62,
//   mpid: 62,
//   name: 'Test Navigation21',
//   router: '/navigation/navigation2/navigation1',
// },
// {
//   id: 622,
//   bpid: 62,
//   mpid: 62,
//   name: 'Test Navigation22',
//   router: '/navigation/navigation2/navigation2',
// },
